# Estimator

학습 : fit()
예측 : predict()

### 분류구현 클래스
DecisionTreeClassifier<br>
RandomForestClassifier<br>
GradientBoostingClassifer<br>
GaussianNB<br>
SVC<br>

### 회귀 구현 클래스
LinearRegression<br>
Ridge<br>
Lasso<br>
RandomForestRegressor<br>
GradientBoostingRegressor

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [13]:
import pandas as pd

In [14]:
iris = load_iris()

In [15]:
iris_data = iris.data

In [16]:
iris_label = iris.target
print('iris target 값 :',iris_label)
print('iris target 명 :',iris.target_names)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 : ['setosa' 'versicolor' 'virginica']


In [17]:
iris_df = pd.DataFrame(data = iris_data , columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

# 데이터 셋트 분리

In [18]:
X_train,X_test,y_train,y_test = train_test_split(iris_data,iris_label,
                                               test_size = 0.2 , random_state = 11) # 0.2 전체중 테스트 20% 학습 80% 분할

In [19]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state = 11)

# 모델학습

In [20]:
# 학습 수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

# 예측수행

In [21]:
# 학습된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

# 평가

In [22]:
from sklearn.metrics import accuracy_score

print("예측 정확도 : {0:.4f}".format(accuracy_score(y_test,pred)))

예측 정확도 : 0.9333


1. 데이터 세트 분리 : 데이터를 학습데이터와 테스트 데이터로 분리
2. 모델 학습 : 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습 시킨다
3. 예측 수행 : 학습된 ML 모델을 이용해서 테스트 데이터의 분류( 즉 ,  붓꽃 종류) 를 예측
4. 평가 : 이렇게 예측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가

# 분류 (Classifier) + 회귀 (Regressor) = Estimator

### 분류나 회귀 연습용 데이터
datasets.load_boston() = 회귀용도 , 미국 보스턴의 집 피처들과 가격에 대한 데이터 세트 <br>
datasets.load_breast_cancer() = 분류용도 , 위스콘신 유방암 피처들과 악성/음성 레이블 데이터 세트<br>
datasets.load_diabetes() = 회귀용도 , 당뇨데이터세트<br>
datasets.load_digits() = 분류용도 , 0에서 9까지 숫자의 이미 픽셀 데이터 세트<br>
datasets.load_iris() = 분류용도  , 붓꽃에 대한 피처를 가진 데이터 세트<br>

### 추후
fetch 계열 데이터 크기가 커서 따로 내려받아야함 

### 분류와 클러스터링을 위한 표본 데이터 생성기
#### datasets.make_classifications()<br>
분류를 위한 데이터 세트를 만든다. 특히 높은 상관도 , 불필요한 속성등의 노이즈 효과를 위한 데이터를 무작위로 생성해준다.<br>
#### datasets.make_blobs()<br>
클러스터링을 위한 데이터세트를 무작위로 생성 , 군집 지정개수에 따라 여러가지 클러스터링을 위한 데이터 세트를 쉽게 만들어준다.


data는 피처의 데이터 세트를 가리킨다<br>
target은 분류시 레이블 값 회귀일때 숫자 결괏값 데이터 세트<br>
target_names는 개별 레이블의 이름을 나타낸다<br>
feature_names는 피처의 이름<br>
DESCR은 데이터세트에 대한 설명과 각 피처의 설명

In [1]:
# 붓꽃데이터 세트 생성
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [4]:
keys = iris_data.keys()
print("붓꽃 데이 세트의 키들:",keys)

붓꽃 데이 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
# load_irs() 가 반환하는 객체의 키인  'feature_names','target_names','data', 'target' 이 가리키는 값을 출력
print('\n feature_names의 type:',type(iris_data.feature_names)) #리스트 타입
print(' feature_names의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 tpye:',type(iris_data.target_names)) #넘파이 어레이 타입
print( 'target_names의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type은 : ',type(iris_data.data)) #넘파이 어레이 타입
print( 'data의 shape : ',len(iris_data.data))
print(iris_data.data)

print('\n target의 type은 :',type(iris_data.target)) #넘파이 어레이 타이뷰
print( 'target의 shape :',len(iris_data.target))
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 tpye: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type은 :  <class 'numpy.ndarray'>
data의 shape :  150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5

# 학습 / 테스트 데이터 세트 분리 -train_test_split()

In [10]:
# 붓꽃
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label= iris.target
dt_clf.fit(train_data,train_label)

#  학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print("예측 정확도 : ",accuracy_score(train_label,pred)) # 100프로가 절대 나올수가 없음

예측 정확도 :  1.0


# 분리
test_size : 테스트 데이터 세트 크기 설정 /디폴트 0.25 <br>
train_size : 학습용 데이터 세트 크기 설정 /(test_size를 통상적으로 사용해서 잘 안씀)<br>
shuffle : 데이터 분리전 데이터를 섞을지 설정 /디폴트 True<br>
randomstate : 동일한 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값 train_test_split는 호출시 무작위로 데이터분리함

train_test_split() 의 반환값은 튜플 형태 
1. 순차적으로  학습용 데이터의 피처데이터
2. 테스트용 데이터의 피처 데이터셋 
3. 학습용 데이터의 레이블 데이터셋
4. 테스트용 데이터의 레이블 데이터 세트가 반환된다

In [15]:
# 붓꽃

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()
# 전체의 30% 테스트 데이터 70%를 학습용 데이터 
X_train,X_test,y_train,y_test = train_test_split(iris_data.data , iris_data.target,
                                                test_size = 0.3 ,random_state=121)

In [16]:
# DecisionTreeClassifier를 학습하고 예측정확도 측정
dt_clf.fit(X_train,y_train)
pred = dt_clf.predict(X_test)

print("예측 정확도 : {0:.4f}".format(accuracy_score(y_test,pred)))

예측 정확도 : 0.9556


# 교차 검증 
과적합 등 성능저하의 우려가 있기 때문에 교차검증이 필요하다

-폴드 교차검증